#-----------------------------------------------------------------------#
#  _________                   __________.__                            #
#/   _____/_____   ____   ____\______   \  | _____  ___.__. ___________ #
#\_____  \\____ \_/ __ \_/ ___\|     ___/  | \__  \<   |  |/ __ \_  __ \#
#/        \  |_> >  ___/\  \___|    |   |  |__/ __ \\___  \  ___/|  | \/#
#  /_______  /   __/ \___  >\___  >____|   |____(____  / ____|\___  >__|#
#  \/|__|        \/     \/                   \/\/         \/            #
#-----------------------------------------------------------------------#

# Choose a storage system (mysql or yaml)
storage-system: yaml

mysql:
  host: "localhost"
  port: 3306
  database: specplayer
  username: "specplayer"
  password: ""