name: SpecPlayer
version: @version@
main: dev.meinel.leo.specplayer.SpecPlayer
api-version: 1.17
authors: [ Leopold Meinel ]
description: Gives you the ability to spectate players.
commands:
  spec:
    description: "Main command"
    usage: "/spec <player>"
permissions:
  specplayer.spectate:
    description: "Permission to spectate players"
    default: op
